import type { Locale } from "@/lib/i18n";

type Category = { title: string; body: string; activities: string[] };
export type ServiceOffering = {
  eyebrow: string;
  title: string;
  introduction: string;
  categories: Category[];
  accountOwnership: { title: string; body: string; points: string[] };
  readinessNote: string;
};

type Audience = "developers" | "agents";
const developerCategories = (locale: Locale): Category[] => locale === "de" ? [
  { title: "Strategie und Marktintelligenz", body: "Öffentlich verfügbare Markt- und Wettbewerbsinformationen fließen nachvollziehbar in Positionierung, Angebotslogik und Marketingentscheidungen ein.", activities: ["Standort-, Zielgruppen- und Vergleichsprojektanalyse", "Beobachtung sichtbarer Wettbewerbsprojekte und Angebote", "Projektpositionierung, Differenzierung und laufende Marktbeobachtung"] },
  { title: "Projektauftritt und Projektwebsite", body: "Die Projektwebsite ist ein integrierter Teil der Vermarktungsstrecke, kein allgemeines Webdesign-Angebot.", activities: ["Individuelles Premium-Design, Einheiten, Grundrisse und Lage", "Verfügbarkeit, Anfrage- und Terminwege", "Mehrsprachigkeit, SEO, Analytics, Conversion-Optimierung und Pflege"] },
  { title: "Google Ads und Suchnachfrage", body: "Suchkampagnen werden rund um reale Projekt-, Lage- und Bedarfssignale aufgebaut und nach Leadqualität weiterentwickelt.", activities: ["Keyword-Recherche, Struktur, Anzeigentexte und Negativ-Keywords", "Suchbegriffs-Reviews, Conversion-Tracking und Landingpages", "Budget- und Gebotsoptimierung mit kontinuierlichem Monitoring"] },
  { title: "Meta Ads und Nachfrageaufbau", body: "Facebook- und Instagram-Kampagnen verbinden Botschaft, Creatives und Lead-Strecke unter Berücksichtigung der anwendbaren Regeln für Wohnungsanzeigen.", activities: ["Kampagnenkonzept, Zielgruppenstrategie, Creatives und Copy", "Lead-Kampagnen und zulässiges Retargeting", "Creative-Tests, Performanceanalyse und Budgetoptimierung"] },
  { title: "Lead- und Interessentenmanagement", body: "Anfragen werden dokumentiert, priorisiert und mit klarem Projektbezug für den Vertrieb vorbereitet.", activities: ["Lead-Erfassung und Quellenzuordnung", "Qualifizierung nach Präferenzen, Budget, Timing und Projektfit", "Follow-up, Terminkoordination, CRM-Dokumentation und Sales-Handover"] },
  { title: "Kommunikation und Vertriebssupport", body: "Interessenten erhalten strukturierte Antworten, während Ihr Vertrieb den Kontext nicht erneut erheben muss.", activities: ["E-Mail-Kommunikation und Informationsanfragen", "Website-Chat mit freigegebenem Projektwissen", "Mehrsprachige Gespräche, Terminwünsche, Eskalation und menschliche Aufsicht"] },
  { title: "Reporting und kontinuierliche Optimierung", body: "Kampagnensignale und Vertriebsrückmeldung verbessern konkrete Hebel wie Suchbegriffe, Creatives, Formulare, Follow-up und Landingpages.", activities: ["Ausgaben, Leads, Leadqualität und Kosten pro Lead", "Termin- und Conversion-Betrachtung", "Regelmäßige Empfehlungen und Prioritäten für die nächste Optimierungsrunde"] }
] : locale === "es" ? [
  { title: "Estrategia e inteligencia de mercado", body: "La información pública de mercado y competencia se incorpora de forma trazable al posicionamiento y las decisiones de marketing.", activities: ["Análisis de ubicación, público y proyectos comparables", "Seguimiento de proyectos y ofertas visibles de competidores", "Posicionamiento, diferenciación y observación continua"] },
  { title: "Presentación y web de promoción", body: "La web de la promoción forma parte del recorrido comercial, no es diseño web generalista.", activities: ["Diseño premium, unidades, planos y ubicación", "Disponibilidad, solicitudes y citas", "Contenido multilingüe, SEO, analítica, conversión y mantenimiento"] },
  { title: "Google Ads y demanda de búsqueda", body: "Las campañas se construyen a partir de señales reales de proyecto, ubicación y demanda, y se mejoran por calidad.", activities: ["Palabras clave, estructura, textos y palabras negativas", "Términos de búsqueda, conversiones y landing pages", "Optimización de presupuesto y pujas con seguimiento continuo"] },
  { title: "Meta Ads y generación de demanda", body: "Facebook e Instagram conectan mensajes, creatividades y captación respetando las restricciones aplicables a vivienda.", activities: ["Concepto, audiencias, creatividades y textos", "Leads y retargeting permitido", "Pruebas creativas, análisis y optimización de presupuesto"] },
  { title: "Gestión de oportunidades", body: "Las solicitudes se documentan y priorizan con un contexto claro para el equipo comercial.", activities: ["Captación y atribución de origen", "Cualificación por preferencias, presupuesto, plazo y encaje", "Seguimiento, citas, CRM y traspaso comercial"] },
  { title: "Comunicación y apoyo comercial", body: "El interesado recibe respuestas estructuradas y el equipo no tiene que reconstruir el contexto.", activities: ["Correo e información solicitada", "Chat web con conocimiento autorizado del proyecto", "Conversaciones multilingües, citas, escalado y supervisión humana"] },
  { title: "Informes y optimización continua", body: "Las señales de campaña y ventas mejoran términos, creatividades, formularios, seguimiento y landing pages.", activities: ["Gasto, leads, calidad y coste por lead", "Citas y conversión", "Recomendaciones y prioridades para cada ciclo de mejora"] }
] : [
  { title: "Strategy and market intelligence", body: "Publicly available market and competitor information informs traceable positioning and marketing decisions.", activities: ["Location, audience and comparable-project analysis", "Monitoring visible competitor projects and public offers", "Project positioning, differentiation and ongoing market observation"] },
  { title: "Project presentation and project websites", body: "The project website is an integrated marketing component, not a general web-design offer.", activities: ["Premium design, units, floor plans and location", "Availability, enquiry and appointment paths", "Multilingual content, SEO, analytics, conversion optimisation and maintenance"] },
  { title: "Google Ads and search demand", body: "Campaigns are built around real project, location and demand signals, then refined by lead quality.", activities: ["Keyword research, structure, ad copy and negative keywords", "Search-term reviews, conversion tracking and landing pages", "Budget and bid optimisation with continuous monitoring"] },
  { title: "Meta Ads and demand creation", body: "Facebook and Instagram connect messages, creative and lead paths while respecting applicable housing-advertising restrictions.", activities: ["Campaign concepts, audiences, creative and copy", "Lead campaigns and permitted retargeting", "Creative testing, performance analysis and budget optimisation"] },
  { title: "Lead and prospect management", body: "Enquiries are documented and prioritised with clear project context for sales.", activities: ["Lead capture and source attribution", "Qualification by preferences, budget, timing and project fit", "Follow-up, appointment coordination, CRM documentation and sales handover"] },
  { title: "Communication and sales support", body: "Prospects receive structured answers while sales does not have to rediscover the context.", activities: ["Email communication and information requests", "Website chat with approved project knowledge", "Multilingual conversations, appointments, escalation and human oversight"] },
  { title: "Reporting and continuous optimisation", body: "Campaign signals and sales feedback improve practical levers such as terms, creative, forms, follow-up and landing pages.", activities: ["Spend, leads, lead quality and cost per lead", "Appointment and conversion analysis", "Recommendations and priorities for each optimisation cycle"] }
];

const agentCategories = (locale: Locale): Category[] => locale === "de" ? [
  { title: "Verkäufergewinnung", body: "Für Eigentümer entsteht ein nachvollziehbarer Weg von der Aufmerksamkeit zum qualifizierten Erstgespräch.", activities: ["Eigentümer-Kampagnen und regionale Positionierung", "Bewertungs- und Verkäufer-Landingpages", "Qualifizierung von Verkaufsabsicht, Objekt und Zeitrahmen", "Terminvereinbarung und dokumentiertes Follow-up"] },
  { title: "Käufergewinnung und Objektvermarktung", body: "Für konkrete Objekte verbinden wir Präsentation, Nachfrageaufbau und qualifizierte Besichtigungsanfragen.", activities: ["Objektkampagnen und Anfragewege", "Käuferprofil, Budget, Finanzierung und Timing", "Besichtigungswünsche, Terminmanagement und Follow-up"] },
  { title: "Performance-Marketing und Marktanalyse", body: "Google Ads, Meta Ads und Social Media werden mit regionaler Markt- und Wettbewerbsbeobachtung verbunden – ohne vertrauliche Daten anderer Marktteilnehmer zu beanspruchen.", activities: ["Suchkampagnen, Meta-Kampagnen und Social Content", "Regionale Markt- und Angebotsanalyse", "Sichtbare Wettbewerbsaktivitäten, Creatives, Copy und Landingpages", "Laufende Kampagnen- und Budgetoptimierung"] },
  { title: "Lead-Bearbeitung und Kundenkommunikation", body: "Anfragen werden nach Segment und Gesprächsreife geordnet, damit Teams weniger Zeit mit unstrukturiertem Nachfassen verbringen.", activities: ["Quellenzuordnung und Priorisierung", "Qualifizierung von Käufer- und Verkäuferinteressen", "E-Mail-Follow-up, Website-Chat, Terminwünsche, Eskalation und Handover"] },
  { title: "Sales Administration, Reporting und Optimierung", body: "Der Prozess unterstützt die tägliche Koordination und eine kontinuierliche Verbesserung von Marketing und Vertrieb.", activities: ["Workflow- und Aufgabenunterstützung", "Follow-up- und Terminübersicht", "Kampagnen-, Lead- und Terminreporting", "Kosten- und Conversion-Betrachtung mit klaren nächsten Prioritäten"] }
] : locale === "es" ? [
  { title: "Captación de propietarios", body: "Construimos un recorrido trazable desde la atención hasta la primera conversación cualificada.", activities: ["Campañas para propietarios y posicionamiento regional", "Landing pages de valoración y captación", "Cualificación de intención, inmueble y plazo", "Citas y seguimiento documentado"] },
  { title: "Captación de compradores y comercialización", body: "Para inmuebles activos unimos presentación, demanda y solicitudes de visita cualificadas.", activities: ["Campañas y vías de solicitud", "Perfil, presupuesto, financiación y plazo", "Visitas, gestión de citas y seguimiento"] },
  { title: "Marketing de resultados y análisis", body: "Google Ads, Meta Ads y redes sociales se combinan con observación regional, sin afirmar acceso a información confidencial de terceros.", activities: ["Búsqueda, Meta y contenidos sociales", "Análisis regional de mercado y oferta", "Actividad visible de competidores, creatividades, textos y landing pages", "Optimización continua de campañas y presupuesto"] },
  { title: "Gestión de oportunidades y comunicación", body: "Las solicitudes se ordenan por segmento y madurez para reducir el seguimiento desestructurado.", activities: ["Origen y priorización", "Cualificación de compradores y propietarios", "Correo, chat web, citas, escalado y traspaso comercial"] },
  { title: "Administración comercial, informes y mejora", body: "El proceso apoya la coordinación diaria y mejora marketing y ventas de forma continua.", activities: ["Flujo y tareas", "Seguimiento y citas", "Informes de campaña, lead y cita", "Coste, conversión y prioridades de mejora"] }
] : [
  { title: "Seller acquisition", body: "We build a traceable path from attention to a qualified first conversation for homeowners.", activities: ["Homeowner campaigns and regional positioning", "Valuation and seller landing pages", "Qualification of selling intent, property and timeline", "Appointment generation and documented follow-up"] },
  { title: "Buyer acquisition and property marketing", body: "For active listings, we connect presentation, demand generation and qualified viewing requests.", activities: ["Property campaigns and enquiry paths", "Buyer profile, budget, financing and timing", "Viewing requests, appointment management and follow-up"] },
  { title: "Performance marketing and market analysis", body: "Google Ads, Meta Ads and social media are connected to regional observation without claiming access to competitors’ confidential data.", activities: ["Search campaigns, Meta campaigns and social content", "Regional market and public-offer analysis", "Visible competitor activity, creative, copy and landing pages", "Continuous campaign and budget optimisation"] },
  { title: "Lead handling and client communication", body: "Enquiries are organised by segment and readiness so teams spend less time on unstructured follow-up.", activities: ["Source attribution and prioritisation", "Buyer and seller qualification", "Email follow-up, website chat, appointments, escalation and sales handover"] },
  { title: "Sales administration, reporting and optimisation", body: "The process supports daily coordination and continuous improvement across marketing and sales.", activities: ["Workflow and task support", "Follow-up and appointment overview", "Campaign, lead and appointment reporting", "Cost, conversion and next-priority analysis"] }
];

const account = (locale: Locale, audience: Audience): ServiceOffering["accountOwnership"] => locale === "de" ? {
  title: audience === "developers" ? "Ihre Werbekonten. Ihr Budget. Volle Transparenz." : "Transparente Werbeausgaben in Ihren Konten.",
  body: "Werbebudgets werden nicht über NovaLure-Konten abgewickelt. Sie behalten Datenhoheit und eine nachvollziehbare Abrechnung.",
  points: ["Google- und Meta-Konten bleiben beim Kunden", "Plattformbudgets werden direkt bezahlt", "NovaLure arbeitet mit vereinbarten Partner- oder Agenturberechtigungen", "Zugriffe, Tracking und Reporting werden im Mandat dokumentiert"]
} : locale === "es" ? {
  title: "Sus cuentas publicitarias. Su presupuesto. Transparencia total.",
  body: "La inversión publicitaria no pasa por cuentas de NovaLure. Conserva la titularidad de los datos y una facturación trazable.",
  points: ["Las cuentas de Google y Meta son del cliente", "Los presupuestos se pagan directamente a las plataformas", "NovaLure trabaja con permisos de socio o agencia acordados", "Accesos, medición e informes se documentan por encargo"]
} : {
  title: audience === "developers" ? "Your ad accounts. Your budget. Full transparency." : "Transparent advertising spend in your own accounts.",
  body: "Advertising spend never passes through NovaLure accounts. You retain data ownership and traceable platform billing.",
  points: ["Google and Meta accounts remain client-owned", "Platform budgets are paid directly", "NovaLure works through agreed partner or agency permissions", "Access, tracking and reporting are documented for the mandate"]
};

export const realEstateServiceOffering: Record<Locale, Record<Audience, ServiceOffering>> = {
  de: {
    developers: { eyebrow: "Integrierte Projektvermarktung", title: "Alle Schritte der digitalen Projektvermarktung – aus einer operativen Verantwortung.", introduction: "NovaLure verbindet Marktverständnis, Projektauftritt, Performance-Marketing, Lead-Bearbeitung und Vertriebssupport. Die Maßnahmen werden entlang des tatsächlichen Projekt- und Vertriebsstands geplant, beobachtet und weiterentwickelt.", categories: developerCategories("de"), accountOwnership: account("de", "developers"), readinessNote: "Vor Aktivierung werden Projekt, Datenzugänge, Einwilligungen, Übergabeweg und operative Verantwortlichkeiten geprüft und vertraglich festgelegt." },
    agents: { eyebrow: "Marketing und Vertriebsunterstützung für Makler", title: "Mehr Struktur zwischen lokaler Nachfrage, Besichtigung und Follow-up.", introduction: "NovaLure verbindet Verkäufer- und Käufergewinnung mit einem klaren Prozess für Qualifizierung, Kommunikation und Übergabe. So wird Marketing nicht vom eigentlichen Immobilienvertrieb getrennt betrachtet.", categories: agentCategories("de"), accountOwnership: account("de", "agents"), readinessNote: "Vor Aktivierung werden Zielgebiet, Objekt- oder Eigentümerprozess, Einwilligungen, Kommunikationsweg und Übergabe an Ihr Team operativ geprüft." }
  },
  en: {
    developers: { eyebrow: "Integrated project marketing", title: "Every step of digital project marketing – under one operating responsibility.", introduction: "NovaLure connects market understanding, project presentation, performance marketing, lead handling and sales support. Activity is planned, observed and refined around the actual project and sales stage.", categories: developerCategories("en"), accountOwnership: account("en", "developers"), readinessNote: "Before activation, the project, data access, consent, handover path and operational responsibilities are checked and agreed contractually." },
    agents: { eyebrow: "Marketing and sales support for real estate agents", title: "More structure between local demand, viewings and follow-up.", introduction: "NovaLure connects seller and buyer acquisition with a clear process for qualification, communication and handover, so marketing is not treated separately from property sales.", categories: agentCategories("en"), accountOwnership: account("en", "agents"), readinessNote: "Before activation, the target area, seller or property process, consent, communication path and handover to your team are checked operationally." }
  },
  es: {
    developers: { eyebrow: "Comercialización integrada de promociones", title: "Todas las fases de la comercialización digital, bajo una misma responsabilidad operativa.", introduction: "NovaLure conecta conocimiento de mercado, presentación, marketing de resultados, gestión de oportunidades y apoyo comercial según la fase real de la promoción.", categories: developerCategories("es"), accountOwnership: account("es", "developers"), readinessNote: "Antes de activar el servicio se verifican proyecto, accesos a datos, consentimiento, ruta de traspaso y responsabilidades operativas, y se fijan por contrato." },
    agents: { eyebrow: "Marketing y apoyo comercial para agencias", title: "Más estructura entre la demanda local, las visitas y el seguimiento.", introduction: "NovaLure conecta la captación de propietarios y compradores con un proceso claro de cualificación, comunicación y traspaso.", categories: agentCategories("es"), accountOwnership: account("es", "agents"), readinessNote: "Antes de activar el servicio se revisan el área objetivo, el proceso de captación o inmueble, consentimiento, comunicación y traspaso al equipo." }
  }
};
