export const relaunchCopy = {
  "de": {
    "navA": "Bauträger",
    "navB": "Makler",
    "navC": "Prozess",
    "navD": "System",
    "navE": "Playbook",
    "login": "CRM-Login",
    "cta": "Projekt-Check anfragen",
    "kicker": "Projektvermarktung mit Vertriebsstruktur",
    "heroH1": "Ihr Projekt verdient Käufer – nicht Kontaktlisten.",
    "heroSub": "NovaLure übernimmt für Bauträger den kompletten Weg von der Projektpräsenz bis zum qualifizierten Käufergespräch: Storytelling, Visualisierung, Exposé, Kampagne, Follow-up und die systemgestützte Übergabe an Ihren Vertrieb.",
    "ctaPlaybook": "Playbook ansehen",
    "trust": "Rooted in Ireland · Aktiv in DACH, UK & international",
    "mockTitle": "NovaLure CRM · Demo-Vertriebspipeline",
    "demoBadge": "Beispiel",
    "demoNote": "Beispielansicht – keine echten Kundendaten",
    "chipKicker": "Referenzen",
    "scoreLabel": "Bewertung",
    "unitPenthouseA3": "Penthouse A3",
    "unitGardenB1": "Gartenwohnung B1",
    "unitDuplexC2": "Maisonette C2",
    "unitApartmentD4": "Wohnung D4",
    "unitGardenB2": "Gartenwohnung B2",
    "unitApartmentE1": "Wohnung E1",
    "unitDuplexC1": "Maisonette C1",
    "stViewing": "Besichtigung",
    "stQualified": "Qualifiziert",
    "stFollowup": "Nachfassen",
    "stHandover": "Übergabe an Vertrieb",
    "stDocs": "Unterlagen ausstehend",
    "srcCampaign": "Quelle: Kampagne",
    "srcBrochure": "Quelle: Exposé-Anfrage",
    "srcLanding": "Quelle: Projektseite",
    "srcReferral": "Quelle: Empfehlung",
    "next1": "Finanzierungsgespräch, Do 14:00",
    "next2": "Rückruf vereinbart, Fr 10:30",
    "next3": "Unterlagen versendet, Rückmeldung offen",
    "next4": "Notartermin in Abstimmung",
    "kpi1": "qualifizierte Anfragen / Monat",
    "kpi2": "Provisionsvolumen aus aktiven Mandaten",
    "proofNote": "Referenzwert aus laufendem Mandat – GRASL Immobilien",
    "bauKicker": "Für Bauträger",
    "bauH": "Sie bauen. Wir sorgen dafür, dass verkauft wird.",
    "probLabel": "Problem",
    "solLabel": "Lösung",
    "pairs": [
      {
        "p": "Anfragen kommen unsortiert aus Portalen, Website und Kampagnen.",
        "s": "Jede Anfrage wird erfasst, bewertet und bekommt einen nächsten Schritt – nichts versandet."
      },
      {
        "p": "Der Vertrieb telefoniert Listen ab statt zu verkaufen.",
        "s": "Übergeben werden nur qualifizierte Gespräche mit Score, Quelle, Budget-Nähe und Timing."
      },
      {
        "p": "Marketing, Exposé und Vertrieb arbeiten getrennt.",
        "s": "Ein System verbindet alles – vom ersten Rendering bis zum Notartermin ist der Faden dokumentiert."
      }
    ],
    "bauResult": "Ergebnis: planbarer Abverkauf statt Bauchgefühl.",
    "procKicker": "Der Prozess",
    "procH": "Sechs Schritte. Ein System. Ein Ansprechpartner.",
    "getLabel": "Das bekommen Sie:",
    "steps": [
      {
        "n": "01",
        "t": "Storytelling",
        "d": "Positionierung und Erzähllinie des Projekts, bevor das erste Asset entsteht.",
        "g": "Projektstory, Zielgruppendefinition, Botschaften-Set."
      },
      {
        "n": "02",
        "t": "Visualisierung",
        "d": "Renderings und Bildwelt, die das Projekt vor Fertigstellung greifbar machen.",
        "g": "Außen- und Innenvisuals in Verkaufsqualität."
      },
      {
        "n": "03",
        "t": "Exposé",
        "d": "Digitale Exposés mit klarer Struktur: Einheiten, Ausstattung, Prozess.",
        "g": "Exposé, das informiert und gleichzeitig vorqualifiziert."
      },
      {
        "n": "04",
        "t": "Kampagne",
        "d": "Zielgruppengenaue Kampagnen in DACH, UK und international.",
        "g": "Reichweite bei kaufbereiten Zielgruppen, nicht bei Klick-Touristen."
      },
      {
        "n": "05",
        "t": "Follow-up",
        "d": "Systematische Nachfassung: jede Anfrage wird qualifiziert oder geschlossen.",
        "g": "Kein Lead bleibt liegen, jeder hat Status und Termin."
      },
      {
        "n": "06",
        "t": "Übergabe",
        "d": "Qualifizierte Gespräche für Ihren Vertrieb.",
        "g": "Score, Quelle, Timing, Budget-Nähe und nächster Schritt – dokumentiert."
      }
    ],
    "procNote": "Sie können den gesamten Weg buchen oder einzelne Module – der Projekt-Check zeigt, was bei Ihrem Projekt fehlt.",
    "sysKicker": "Das System dahinter",
    "sysH": "Ihr Vertrieb übernimmt Gespräche, keine Rohkontakte.",
    "sysB1": "Jede Anfrage wird erfasst, bewertet und terminiert — nichts versandet.",
    "sysB2": "Lead-Score, Quelle und Timing machen Priorisierung objektiv.",
    "sysB3": "Übergabe mit Kontext: Score, Quelle und nächster Schritt sind dokumentiert.",
    "pipeTitle": "Vertriebsübersicht",
    "colA": "Neue Anfragen",
    "colB": "Qualifiziert",
    "colC": "Besichtigungen",
    "caseKicker": "Referenz",
    "c1t": "Ausgangslage",
    "c1": "Unfilterte Kontakte, keine Priorisierung, Pipeline nicht planbar.",
    "c2t": "Was wir aufgebaut haben",
    "c2": "Lead-Pfad mit Qualifizierung, Follow-up-Struktur und Übergabe ins CRM.",
    "c3t": "Ergebnis",
    "c3": "15–20 qualifizierte Anfragen/Monat, EUR 110k+ Provisionsvolumen, planbare Pipeline.",
    "quote": "„Wir bekommen keine Kontaktlisten, sondern vorbereitete Gespräche. Das ist der Unterschied.\"",
    "mkKicker": "Für Makler & Teams",
    "mkH": "Auch für Makler, die Projekte übernehmen.",
    "mkBody": "Sie vermarkten Bauträgerprojekte oder wollen Ihre Anfragenqualität heben? Derselbe Prozess arbeitet für Sie: Sie übernehmen vorbereitete Gespräche statt Rohkontakte – und treten beim Bauträger mit einem System auf, das Abverkauf planbar macht.",
    "mkCta": "Projekt-Check für Maklerteams anfragen",
    "matKicker": "Material",
    "matH": "So sieht unser Material aus.",
    "matBadge": "Beispiel-Visual",
    "mat1t": "Außenvisualisierung",
    "mat1m": "Beispiel: alpines Neubauprojekt",
    "mat2t": "Innenvisualisierung",
    "mat2m": "Beispiel: Wohnraum & Ausstattung",
    "mat3t": "Exposé & Kampagne",
    "mat3m": "Beispiel: digitales Exposé",
    "trH": "Warum Sie uns vertrauen können",
    "tr1b": "Sie sehen, was Sie bekommen.",
    "tr1": "Visuals und Exposé-Beispiele sind offen – beurteilen Sie die Qualität selbst.",
    "tr2b": "Keine Lead-Versprechen aus der Luft.",
    "tr2": "Anfragenzahlen hängen von Projekt, Markt und Budget ab. Wir nennen keine Fantasiezahlen.",
    "tr3b": "Ein echter Prozess, kein anonymer Funnel.",
    "tr3": "Jede Anfrage bekommt einen nächsten Schritt.",
    "teamKicker": "Wer dahinter steht",
    "teamH": "Ein Ansprechpartner. Ein Team, das liefert.",
    "teamBody": "Franz Romih führt jedes Mandat persönlich — von der ersten Projektanalyse bis zur Übergabe an den Vertrieb. Dahinter arbeitet ein Team aus Spezialisten für Visualisierung, Kampagne und Vertriebssystematik.",
    "tagA": "Visualisierung",
    "tagB": "Kampagne",
    "tagC": "Vertriebssystematik",
    "pbKicker": "Playbook",
    "pbH": "Das NovaLure Playbook",
    "pbBody": "Wie aus Projektpräsenz qualifizierte Käufergespräche werden: der Prozess, die Kennzahlen, die Übergabe. Kompakt und ohne Marketing-Superlative.",
    "pbPh": "E-Mail-Adresse",
    "pbBtn": "Playbook erhalten",
    "pbGdpr": "Ich bin einverstanden, dass NovaLure mich per E-Mail kontaktiert. Abmeldung jederzeit möglich. Details:",
    "pbDone": "Danke — das Playbook ist unterwegs.",
    "pbCover": "Vom Projekt zum Gespräch",
    "finalH": "30 Minuten. Wir prüfen Ihren Projektpfad.",
    "finalSub": "Unverbindlich und konkret: Sie erhalten eine klare Einschätzung, keine Verkaufspräsentation.",
    "fName": "Name",
    "fMail": "E-Mail",
    "fType": "Projektart",
    "fOpt1": "Neubauprojekt",
    "fOpt2": "Bestand",
    "fOpt3": "Maklerteam",
    "fMsg": "Nachricht (optional)",
    "fBtn": "Projekt-Check anfragen",
    "fDone": "Danke — wir melden uns kurzfristig.",
    "footTag": "Projektvermarktung mit Vertriebsstruktur. Rooted in Ireland, aktiv in DACH, UK & international.",
    "footPages": "Seiten",
    "footLegal": "Rechtliches",
    "footNews": "Newsletter",
    "footNewsSub": "Einblicke in Projektvermarktung — unregelmäßig, ohne Floskeln.",
    "footNewsBtn": "Anmelden",
    "footNewsPh": "E-Mail-Adresse",
    "imprint": "Impressum",
    "privacy": "Datenschutz",
    "cookies": "Cookies",
    "ckSettingsLabel": "Cookie-Einstellungen",
    "footDoi": "Double-Opt-in: Sie bestätigen die Anmeldung per E-Mail.",
    "faqKicker": "Häufige Fragen",
    "faqH": "Was Bauträger uns vor dem ersten Gespräch fragen.",
    "faq": [
      {
        "q": "Was kostet die Zusammenarbeit?",
        "a": "Das hängt vom Projekt ab: Einheitenzahl, vorhandenes Material, gewünschte Module. Wir arbeiten mit transparenten Projektpaketen statt versteckter Prozente – im Projekt-Check bekommen Sie eine konkrete Einschätzung, was Ihr Projekt braucht und was das kostet. Keine Kosten für das Erstgespräch."
      },
      {
        "q": "Wie schnell können Sie starten?",
        "a": "Nach dem Projekt-Check erhalten Sie innerhalb weniger Tage einen konkreten Fahrplan. Erste Assets wie Storytelling und Visualisierungs-Briefing starten in der Regel innerhalb von zwei Wochen nach Beauftragung."
      },
      {
        "q": "Wir haben bereits einen Makler – passt das zusammen?",
        "a": "Ja, das ist sogar der Normalfall. Wir ersetzen Ihren Vertrieb nicht, wir bereiten ihn vor: Ihr Makler oder Ihr internes Team übernimmt qualifizierte Gespräche mit Score, Quelle und nächstem Schritt – statt Kontaktlisten abzutelefonieren."
      },
      {
        "q": "Müssen wir den ganzen Prozess buchen?",
        "a": "Nein. Sie können den kompletten Weg buchen oder einzelne Module – etwa nur Visualisierung und Exposé, oder nur Follow-up und Übergabe. Der Projekt-Check zeigt, wo bei Ihrem Projekt die Lücke ist."
      },
      {
        "q": "Was passiert im Projekt-Check konkret?",
        "a": "30 Minuten Video-Call. Wir schauen gemeinsam auf Projektpräsenz, Anfragewege, Follow-up und Übergabe an den Vertrieb. Sie erhalten eine klare Einschätzung mit den zwei bis drei größten Hebeln – unabhängig davon, ob wir zusammenarbeiten."
      },
      {
        "q": "In welchen Regionen und Sprachen arbeiten Sie?",
        "a": "Schwerpunkt DACH, dazu UK und internationale Käuferzielgruppen. Material und Kampagnen liefern wir auf Deutsch und Englisch."
      }
    ],
    "bothWays": "Beide Wege führen zum selben Gespräch – nehmen Sie den, der für Sie schneller ist.",
    "calH": "Oder direkt Termin wählen",
    "calSub": "Wählen Sie einen freien 30-Minuten-Slot – ohne E-Mail-Pingpong.",
    "calEmbed": "Kalender-Embed (Cal.com / Calendly)",
    "calBtn": "Termin-Link öffnen",
    "capNote": "Wir betreuen maximal [X] Mandate parallel – damit jedes Projekt die Aufmerksamkeit bekommt, die es braucht.",
    "capDraft": "Entwurf: [X] nur mit echter Zahl veröffentlichen",
    "fPrivacy": "Hinweise zur Verarbeitung Ihrer Daten:",
    "ckText": "Wir verwenden Cookies für Grundfunktionen und – nur mit Ihrer Zustimmung – für Statistik und Marketing. Details in der",
    "ckLink": "Cookie-Richtlinie",
    "ckAll": "Alle akzeptieren",
    "ckNec": "Nur notwendige",
    "ckSet": "Einstellungen",
    "ckSave": "Auswahl speichern",
    "ckCatNec": "Notwendig",
    "ckCatStats": "Statistik",
    "ckCatMkt": "Marketing"
  },
  "en": {
    "navA": "Developers",
    "navB": "Agents",
    "navC": "Process",
    "navD": "System",
    "navE": "Playbook",
    "login": "CRM login",
    "cta": "Request a project check",
    "kicker": "Project marketing with sales structure",
    "heroH1": "Your project deserves buyers – not contact lists.",
    "heroSub": "NovaLure covers the full path for developers, from project presence to qualified buyer conversations: storytelling, visualisation, brochure, campaign, follow-up and a structured handover to your sales team.",
    "ctaPlaybook": "View the playbook",
    "trust": "Rooted in Ireland · Active in DACH, UK & internationally",
    "mockTitle": "NovaLure CRM · Demo pipeline",
    "demoBadge": "Demo",
    "demoNote": "Demo view — no real customer data",
    "chipKicker": "References",
    "scoreLabel": "Score",
    "unitPenthouseA3": "Penthouse A3",
    "unitGardenB1": "Garden Apartment B1",
    "unitDuplexC2": "Duplex C2",
    "unitApartmentD4": "Apartment D4",
    "unitGardenB2": "Garden Apartment B2",
    "unitApartmentE1": "Apartment E1",
    "unitDuplexC1": "Duplex C1",
    "stViewing": "Viewing",
    "stQualified": "Qualified",
    "stFollowup": "Follow-up",
    "stHandover": "Sales handover",
    "stDocs": "Documents pending",
    "srcCampaign": "Source: campaign",
    "srcBrochure": "Source: brochure request",
    "srcLanding": "Source: landing page",
    "srcReferral": "Source: referral",
    "next1": "Financing call, Thu 2pm",
    "next2": "Call-back booked, Fri 10:30",
    "next3": "Documents sent, waiting",
    "next4": "Notary date being scheduled",
    "kpi1": "qualified enquiries / month",
    "kpi2": "commission volume from active mandates",
    "proofNote": "Reference values from an active mandate — GRASL Immobilien",
    "bauKicker": "For developers",
    "bauH": "You build. We make sure it sells.",
    "probLabel": "Problem",
    "solLabel": "Solution",
    "pairs": [
      {
        "p": "Enquiries arrive unsorted from portals, website and campaigns.",
        "s": "Every enquiry is captured, scored and given a next step – nothing slips through."
      },
      {
        "p": "Your sales team works through call lists instead of selling.",
        "s": "Only qualified conversations are handed over – with score, source, budget fit and timing."
      },
      {
        "p": "Marketing, brochure and sales work in silos.",
        "s": "One system connects it all – from first rendering to notary appointment, the thread is documented."
      }
    ],
    "bauResult": "The result: predictable sales instead of gut feeling.",
    "procKicker": "The process",
    "procH": "Six steps. One system. One point of contact.",
    "getLabel": "What you get:",
    "steps": [
      {
        "n": "01",
        "t": "Storytelling",
        "d": "Positioning and narrative for the project, before the first asset is produced.",
        "g": "Project story, target-group definition, message set."
      },
      {
        "n": "02",
        "t": "Visualisation",
        "d": "Renderings and imagery that make the project tangible before completion.",
        "g": "Exterior and interior visuals in sales quality."
      },
      {
        "n": "03",
        "t": "Brochure",
        "d": "Digital brochures with clear structure: units, specification, process.",
        "g": "A brochure that informs and pre-qualifies at the same time."
      },
      {
        "n": "04",
        "t": "Campaign",
        "d": "Precisely targeted campaigns across DACH, UK and internationally.",
        "g": "Reach among ready-to-buy audiences, not click tourists."
      },
      {
        "n": "05",
        "t": "Follow-up",
        "d": "Systematic follow-up: every enquiry is qualified or closed.",
        "g": "No lead is left behind — every one has a status and a date."
      },
      {
        "n": "06",
        "t": "Handover",
        "d": "Qualified conversations for your sales team.",
        "g": "Score, source, timing, budget fit and next step — documented."
      }
    ],
    "procNote": "Book the full path or individual modules – the project check shows what your project is missing.",
    "sysKicker": "The system behind it",
    "sysH": "Your sales team takes over conversations, not raw leads.",
    "sysB1": "Every enquiry is captured, scored and scheduled — nothing slips through.",
    "sysB2": "Lead score, source and timing make prioritisation objective.",
    "sysB3": "Handover with context: score, source and next step are documented.",
    "pipeTitle": "Pipeline view",
    "colA": "New",
    "colB": "Qualified",
    "colC": "Viewing",
    "caseKicker": "Reference",
    "c1t": "Starting point",
    "c1": "Unfiltered contacts, no prioritisation, no predictable pipeline.",
    "c2t": "What we built",
    "c2": "A lead path with qualification, follow-up structure and CRM handover.",
    "c3t": "Result",
    "c3": "15–20 qualified enquiries/month, EUR 110k+ commission volume, a predictable pipeline.",
    "quote": "\"We don’t get contact lists — we get prepared conversations. That’s the difference.\"",
    "mkKicker": "For agents & teams",
    "mkH": "Also for agents taking on developer projects.",
    "mkBody": "You market developer projects, or want to raise the quality of your enquiries? The same process works for you: you take over prepared conversations instead of raw leads – and approach developers with a system that makes sell-out predictable.",
    "mkCta": "Request a project check for agent teams",
    "matKicker": "Material",
    "matH": "What our material looks like.",
    "matBadge": "Sample visual",
    "mat1t": "Exterior visualisation",
    "mat1m": "Example: alpine new-build project",
    "mat2t": "Interior visualisation",
    "mat2m": "Example: living space & specification",
    "mat3t": "Brochure & campaign",
    "mat3m": "Example: digital brochure",
    "trH": "Why you can trust us",
    "tr1b": "You see what you get.",
    "tr1": "Visuals and brochure samples are open – judge the quality yourself.",
    "tr2b": "No lead promises out of thin air.",
    "tr2": "Enquiry numbers depend on project, market and budget. We don’t quote fantasy figures.",
    "tr3b": "A real process, not an anonymous funnel.",
    "tr3": "Every enquiry gets a next step.",
    "teamKicker": "Who is behind it",
    "teamH": "One point of contact. A team that delivers.",
    "teamBody": "Franz Romih leads every mandate personally — from the first project analysis to the sales handover. Behind him works a team of specialists in visualisation, campaigns and sales systems.",
    "tagA": "Visualisation",
    "tagB": "Campaign",
    "tagC": "Sales systems",
    "pbKicker": "Playbook",
    "pbH": "The NovaLure Playbook",
    "pbBody": "How project presence becomes qualified buyer conversations: the process, the metrics, the handover. Compact, no fluff.",
    "pbPh": "Email address",
    "pbBtn": "Get the playbook",
    "pbGdpr": "I agree that NovaLure may contact me by email. Unsubscribe anytime. Details:",
    "pbDone": "Thanks — the playbook is on its way.",
    "pbCover": "From project to conversation",
    "finalH": "30 minutes. We review your project path.",
    "finalSub": "No obligation, and concrete: you get a clear assessment, not a sales pitch.",
    "fName": "Name",
    "fMail": "Email",
    "fType": "Project type",
    "fOpt1": "New-build project",
    "fOpt2": "Existing stock",
    "fOpt3": "Agent team",
    "fMsg": "Message (optional)",
    "fBtn": "Request a project check",
    "fDone": "Thanks — we’ll be in touch shortly.",
    "footTag": "Project marketing with sales structure. Rooted in Ireland, active in DACH, UK & internationally.",
    "footPages": "Pages",
    "footLegal": "Legal",
    "footNews": "Newsletter",
    "footNewsSub": "Insights on project marketing — occasional, no fluff.",
    "footNewsBtn": "Subscribe",
    "footNewsPh": "Email address",
    "imprint": "Imprint",
    "privacy": "Privacy",
    "cookies": "Cookies",
    "ckSettingsLabel": "Cookie settings",
    "footDoi": "Double opt-in: you confirm your subscription by email.",
    "faqKicker": "Frequently asked",
    "faqH": "What developers ask us before the first call.",
    "faq": [
      {
        "q": "What does working together cost?",
        "a": "It depends on the project: number of units, existing material, the modules you need. We work with transparent project packages instead of hidden percentages – in the project check you get a concrete assessment of what your project needs and what it costs. The first conversation is free of charge."
      },
      {
        "q": "How quickly can you start?",
        "a": "After the project check you receive a concrete roadmap within a few days. First assets such as storytelling and the visualisation briefing usually start within two weeks of engagement."
      },
      {
        "q": "We already have an agent – does that fit?",
        "a": "Yes – that’s the normal case. We don’t replace your sales side, we prepare it: your agent or in-house team takes over qualified conversations with score, source and next step – instead of working through call lists."
      },
      {
        "q": "Do we have to book the whole process?",
        "a": "No. You can book the full path or individual modules – say, only visualisation and brochure, or only follow-up and handover. The project check shows where your project’s gap is."
      },
      {
        "q": "What happens in the project check, concretely?",
        "a": "A 30-minute video call. Together we look at project presence, enquiry routes, follow-up and the handover to sales. You get a clear assessment with the two or three biggest levers – whether or not we end up working together."
      },
      {
        "q": "Which regions and languages do you cover?",
        "a": "Focus on DACH, plus the UK and international buyer audiences. We deliver material and campaigns in German and English."
      }
    ],
    "bothWays": "Both routes lead to the same conversation – take whichever is faster for you.",
    "calH": "Or pick a time directly",
    "calSub": "Choose a free 30-minute slot – no email ping-pong.",
    "calEmbed": "Calendar embed (Cal.com / Calendly)",
    "calBtn": "Open booking link",
    "capNote": "We take on a maximum of [X] mandates in parallel – so every project gets the attention it needs.",
    "capDraft": "Draft: publish only with a real number",
    "fPrivacy": "How we process your data:",
    "ckText": "We use cookies for core functionality and – only with your consent – for statistics and marketing. Details in the",
    "ckLink": "cookie policy",
    "ckAll": "Accept all",
    "ckNec": "Necessary only",
    "ckSet": "Settings",
    "ckSave": "Save selection",
    "ckCatNec": "Necessary",
    "ckCatStats": "Statistics",
    "ckCatMkt": "Marketing"
  },
  "es": {
    "navA": "Promotores",
    "navB": "Agencias inmobiliarias",
    "navC": "Proceso",
    "navD": "Sistema",
    "navE": "Playbook",
    "login": "Acceso al CRM",
    "cta": "Solicitar un análisis del proyecto",
    "kicker": "Comercialización de promociones inmobiliarias con una estructura de ventas clara",
    "heroH1": "Su promoción merece compradores, no listas de contactos.",
    "heroSub": "NovaLure estructura todo el recorrido comercial de una promoción inmobiliaria: posicionamiento, visualización, dossier comercial, campaña, seguimiento y traspaso de oportunidades cualificadas al equipo comercial.",
    "ctaPlaybook": "Ver el Playbook",
    "trust": "Con raíces en Irlanda · Activos en Alemania, Austria y Suiza, Reino Unido y mercados internacionales",
    "mockTitle": "NovaLure CRM · Flujo de oportunidades",
    "demoBadge": "Demostración",
    "demoNote": "Demostración: sin datos reales de clientes",
    "chipKicker": "Referencias",
    "scoreLabel": "Puntuación",
    "unitPenthouseA3": "Ático A3",
    "unitGardenB1": "Vivienda con jardín B1",
    "unitDuplexC2": "Dúplex C2",
    "unitApartmentD4": "Vivienda D4",
    "unitGardenB2": "Vivienda con jardín B2",
    "unitApartmentE1": "Vivienda E1",
    "unitDuplexC1": "Dúplex C1",
    "stViewing": "Visita",
    "stQualified": "Cualificado",
    "stFollowup": "Seguimiento",
    "stHandover": "Traspaso comercial",
    "stDocs": "Documentación pendiente",
    "srcCampaign": "Origen: campaña",
    "srcBrochure": "Origen: solicitud del dossier",
    "srcLanding": "Origen: página de destino",
    "srcReferral": "Origen: recomendación",
    "next1": "Llamada sobre financiación, jue. 14:00",
    "next2": "Llamada programada, vie. 10:30",
    "next3": "Documentación enviada, pendiente de respuesta",
    "next4": "Cita en notaría en preparación",
    "kpi1": "solicitudes cualificadas al mes",
    "kpi2": "volumen de comisiones de encargos activos",
    "proofNote": "Valores de referencia de un encargo activo — GRASL Immobilien",
    "bauKicker": "Para promotores",
    "bauH": "Usted desarrolla la promoción. Nosotros estructuramos su comercialización.",
    "probLabel": "Problema",
    "solLabel": "Solución",
    "pairs": [
      {
        "p": "Las solicitudes llegan sin clasificar desde portales, la web y las campañas.",
        "s": "Cada solicitud se registra, se puntúa y recibe un siguiente paso; nada queda sin atender."
      },
      {
        "p": "El equipo comercial llama a listas de contactos en lugar de vender.",
        "s": "Solo se traspasan conversaciones cualificadas, con puntuación, origen, encaje presupuestario y plazo."
      },
      {
        "p": "Marketing, dossier comercial y ventas trabajan por separado.",
        "s": "Un único sistema conecta todo el recorrido, desde la primera visualización hasta la cita en notaría."
      }
    ],
    "bauResult": "Resultado: una comercialización planificable en lugar de decisiones por intuición.",
    "procKicker": "El proceso",
    "procH": "Seis pasos. Un sistema. Un único interlocutor.",
    "getLabel": "Qué recibe:",
    "steps": [
      {
        "n": "01",
        "t": "Estrategia y relato",
        "d": "Posicionamiento y narrativa de la promoción antes de crear el primer activo.",
        "g": "Relato del proyecto, definición del público y mensajes clave."
      },
      {
        "n": "02",
        "t": "Visualización",
        "d": "Imágenes que permiten comprender la promoción antes de su finalización.",
        "g": "Visualizaciones exteriores e interiores con calidad comercial."
      },
      {
        "n": "03",
        "t": "Dossier comercial",
        "d": "Dossieres digitales con una estructura clara de viviendas, calidades y proceso.",
        "g": "Un dossier que informa y precualifica al mismo tiempo."
      },
      {
        "n": "04",
        "t": "Campaña",
        "d": "Campañas dirigidas a públicos concretos en DACH, Reino Unido y mercados internacionales.",
        "g": "Alcance entre públicos con intención de compra, no simples clics."
      },
      {
        "n": "05",
        "t": "Seguimiento",
        "d": "Seguimiento sistemático: cada solicitud se cualifica o se cierra.",
        "g": "Cada oportunidad tiene un estado, un responsable y una fecha."
      },
      {
        "n": "06",
        "t": "Traspaso comercial",
        "d": "Conversaciones cualificadas para su equipo comercial.",
        "g": "Puntuación, origen, plazo, presupuesto y siguiente paso documentados."
      }
    ],
    "procNote": "Puede contratar el recorrido completo o módulos concretos; el análisis del proyecto muestra qué necesita su promoción.",
    "sysKicker": "El sistema que lo hace posible",
    "sysH": "Su equipo comercial recibe conversaciones preparadas, no contactos sin filtrar.",
    "sysB1": "Cada solicitud se registra, se cualifica y recibe un siguiente paso; nada queda sin atender.",
    "sysB2": "La puntuación, el origen y el plazo permiten priorizar con criterios objetivos.",
    "sysB3": "El traspaso conserva el contexto: puntuación, origen y siguiente paso quedan documentados.",
    "pipeTitle": "Resumen comercial",
    "colA": "Nuevo",
    "colB": "Cualificado",
    "colC": "Visita",
    "caseKicker": "Referencia",
    "c1t": "Punto de partida",
    "c1": "Contactos sin filtrar, sin priorización y sin una previsión clara del flujo comercial.",
    "c2t": "Qué implantamos",
    "c2": "Un recorrido con cualificación, seguimiento estructurado y traspaso al CRM.",
    "c3t": "Resultado",
    "c3": "15–20 solicitudes cualificadas al mes, más de 110.000 EUR de volumen de comisiones y un flujo previsible.",
    "quote": "\"No recibimos listas de contactos, sino conversaciones preparadas. Esa es la diferencia.\"",
    "mkKicker": "Para agencias y equipos",
    "mkH": "También para agencias inmobiliarias que comercializan promociones.",
    "mkBody": "¿Comercializa promociones o quiere mejorar la calidad de sus solicitudes? El mismo proceso le permite recibir conversaciones preparadas en lugar de contactos sin filtrar y presentar a los promotores un sistema comercial estructurado.",
    "mkCta": "Solicitar un análisis para la agencia",
    "matKicker": "Material",
    "matH": "Así es nuestro material comercial.",
    "matBadge": "Ejemplo visual",
    "mat1t": "Visualización exterior",
    "mat1m": "Ejemplo: promoción residencial alpina",
    "mat2t": "Visualización interior",
    "mat2m": "Ejemplo: espacio interior y calidades",
    "mat3t": "Dossier y campaña",
    "mat3m": "Ejemplo: dossier comercial digital",
    "trH": "Por qué puede confiar en nosotros",
    "tr1b": "Ve exactamente lo que recibe.",
    "tr1": "Mostramos ejemplos de visualizaciones y dossieres para que pueda valorar la calidad.",
    "tr2b": "Sin promesas de contactos inventadas.",
    "tr2": "El número de solicitudes depende del proyecto, el mercado y el presupuesto. No presentamos cifras irreales.",
    "tr3b": "Un proceso real, no un embudo anónimo.",
    "tr3": "Cada solicitud recibe un siguiente paso.",
    "teamKicker": "Quién está detrás",
    "teamH": "Un único interlocutor. Un equipo que cumple.",
    "teamBody": "Franz Romih dirige personalmente cada encargo, desde el análisis inicial hasta el traspaso al equipo comercial. Le acompaña un equipo especializado en visualización, campañas y sistemas comerciales.",
    "tagA": "Visualización",
    "tagB": "Campaña",
    "tagC": "Sistemas comerciales",
    "pbKicker": "Playbook",
    "pbH": "El Playbook de NovaLure",
    "pbBody": "Cómo convertir la presencia de una promoción en conversaciones cualificadas con compradores: proceso, métricas y traspaso. Claro y sin superlativos.",
    "pbPh": "Correo electrónico",
    "pbBtn": "Recibir el Playbook",
    "pbGdpr": "Consiento que NovaLure me contacte por correo electrónico. Puedo darme de baja en cualquier momento. Más información:",
    "pbDone": "Gracias. El Playbook está de camino.",
    "pbCover": "De la promoción a la conversación",
    "finalH": "30 minutos para revisar su recorrido comercial.",
    "finalSub": "Sin compromiso y de forma concreta: recibirá una valoración clara, no una presentación comercial.",
    "fName": "Nombre",
    "fMail": "Correo electrónico",
    "fType": "Tipo de proyecto",
    "fOpt1": "Promoción de obra nueva",
    "fOpt2": "Inmueble existente",
    "fOpt3": "Agencia inmobiliaria",
    "fMsg": "Mensaje (opcional)",
    "fBtn": "Solicitar un análisis del proyecto",
    "fDone": "Gracias. Nos pondremos en contacto en breve.",
    "footTag": "Comercialización de promociones con estructura comercial. Con raíces en Irlanda y activos en DACH, Reino Unido y mercados internacionales.",
    "footPages": "Páginas",
    "footLegal": "Información legal",
    "footNews": "Novedades",
    "footNewsSub": "Ideas prácticas sobre comercialización inmobiliaria, sin ruido.",
    "footNewsBtn": "Suscribirse",
    "footNewsPh": "Correo electrónico",
    "imprint": "Aviso legal",
    "privacy": "Privacidad",
    "cookies": "Cookies",
    "ckSettingsLabel": "Configuración de cookies",
    "footDoi": "Doble confirmación: confirme la suscripción por correo electrónico.",
    "faqKicker": "Preguntas frecuentes",
    "faqH": "Lo que los promotores nos preguntan antes de la primera conversación.",
    "faq": [
      {
        "q": "¿Cuánto cuesta trabajar con NovaLure?",
        "a": "Depende de la promoción, el número de viviendas, el material existente y los módulos necesarios. Trabajamos con propuestas transparentes y el análisis inicial permite concretar alcance y coste. La primera conversación no tiene coste."
      },
      {
        "q": "¿Cuándo pueden empezar?",
        "a": "Tras el análisis del proyecto recibirá una hoja de ruta concreta en pocos días. Los primeros trabajos suelen comenzar dentro de las dos semanas siguientes a la contratación."
      },
      {
        "q": "Ya trabajamos con una agencia inmobiliaria. ¿Es compatible?",
        "a": "Sí. No sustituimos a su equipo comercial: lo preparamos para recibir conversaciones cualificadas con origen, puntuación y siguiente paso."
      },
      {
        "q": "¿Tenemos que contratar todo el proceso?",
        "a": "No. Puede contratar el recorrido completo o módulos concretos. El análisis muestra dónde se encuentra la principal carencia de su promoción."
      },
      {
        "q": "¿Qué ocurre exactamente durante el análisis?",
        "a": "En una videollamada de 30 minutos revisamos la presencia del proyecto, los canales de captación, el seguimiento y el traspaso comercial. Recibirá una valoración clara de los dos o tres puntos con mayor impacto."
      },
      {
        "q": "¿En qué mercados e idiomas trabajan?",
        "a": "Trabajamos principalmente en DACH, Reino Unido y con públicos compradores internacionales. El material y las campañas pueden prepararse en alemán, inglés y español."
      }
    ],
    "bothWays": "Ambas vías llevan a la misma conversación; elija la que le resulte más rápida.",
    "calH": "O elija directamente una fecha",
    "calSub": "Seleccione una franja disponible de 30 minutos, sin intercambios innecesarios de correos.",
    "calEmbed": "Calendario de reservas",
    "calBtn": "Abrir el calendario",
    "capNote": "Trabajamos con un número limitado de encargos simultáneos para dedicar a cada promoción la atención necesaria.",
    "capDraft": "Borrador interno: publicar solo con una cifra confirmada",
    "fPrivacy": "Información sobre el tratamiento de sus datos:",
    "ckText": "Utilizamos cookies necesarias y, solo con su consentimiento, tecnologías de estadística y marketing. Más información en la",
    "ckLink": "Política de cookies",
    "ckAll": "Aceptar todas",
    "ckNec": "Solo necesarias",
    "ckSet": "Configurar",
    "ckSave": "Guardar selección",
    "ckCatNec": "Necesarias",
    "ckCatStats": "Estadísticas",
    "ckCatMkt": "Marketing"
  }
} as const;

export type RelaunchLocale = keyof typeof relaunchCopy;
